trigger:
- main

pool:
  name: self-hosted-pool

variables:
- name: region
  value: europe
- name: rules_path
  value: rules

steps:
- script: |
    python3 -m pip install --upgrade pip
    if [ -f scripts/python/requirements.txt ]; then pip3 install -r scripts/python/requirements.txt; fi
  displayName: "Install dependencies"

- script: |
    python3 scripts/python/rules.py -e SA_CREDENTIAL -l $(rules_path) -s -r $(region)
  displayName: Pre-upload dry run
  env:
    SA_CREDENTIAL: $(SA_CREDENTIAL)

- script: |
    python3 scripts/python/rules.py -e SA_CREDENTIAL -l $(rules_path) -s -r $(region) -m
  displayName: Upload/update any rules
  env:
    SA_CREDENTIAL: $(SA_CREDENTIAL)

- script: |
    python3 scripts/python/rules.py -e SA_CREDENTIAL -l $(rules_path) -s -r $(region)
  displayName: Post-upload dry run
  env:
    SA_CREDENTIAL: $(SA_CREDENTIAL)

