steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "scripts/python/requirements.txt", "--user"]

  # Pre-upload dry run
  - name: python
    entrypoint: python
    args: ["scripts/python/rules.py", "-e", "SA_CREDENTIAL", "-l", "$_RULES_PATH", "-s", "-r", "$_REGION"]
    secretEnv: ['SA_CREDENTIAL']

  # Upload/update any rules
  - name: python
    entrypoint: python
    args: ["scripts/python/rules.py", "-e", "SA_CREDENTIAL", "-l", "$_RULES_PATH", "-s", "-r", "$_REGION", "-m"]
    secretEnv: ['SA_CREDENTIAL']

  # Post-upload dry run
  - name: python
    entrypoint: python
    args: ["scripts/python/rules.py", "-e", "SA_CREDENTIAL", "-l", "$_RULES_PATH", "-s", "-r", "$_REGION"]
    secretEnv: ['SA_CREDENTIAL']

availableSecrets:
  secretManager:
  - env: SA_CREDENTIAL
    versionName: projects/$_PROJECT_ID/secrets/$_SECRET_NAME/versions/latest
    
